version: 0.2

phases:
  install:
    commands:
      - echo "Setting up docker"
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      
  pre_build:
    commands:
      - echo "Running unit tests"
      - cd test
      - go test
      - cd ..

  build:
    commands:
      - echo "Building Docker container for app"
      - systemctl start docker
      # api build
      - docker build -f ./docker/app/Dockerfile -t re-region-api:latest .
      - docker save re-region-api:latest > reregion.tar
      # server build
      - docker build -f ./docker/server/Dockerfile -t re-region-api_nginx:latest .
      - docker save re-region-api_nginx:latest > server.tar

artifacts:
  files:
    - reregion.tar
    - server.tar
    - cmd/docker-compose.yml
    - cmd/runserver.sh
    
  
