openapi: 3.0.3
info:
  title: Re-Region API
  description: |
    API to request information about regions in the United States. The system's goal is to provide access to well structured information that can
    be used to help people research new areas to live in and explore. It has information on demographic and lifestyle stats along with taxation estimates 
    for counties and states.
  version: 0.0.3

servers:
  - url: http://127.0.0.1:8080/
    description: Local server

paths:
  /counties:
    get:
      tags:
        - County
      summary: Get survey statistics and taxation estimates for a given county and tax filing input variables.
      consumes: 
        - application/json
      produces: 
        - application/json
      parameters:
        - in: path
          name: id
          schema: 
            type: integer
            #minimum: 1
            #maximum: 1
          required: false
          description: |
              Numeric id tied to the county in the system. Can be used to identify a county in the request. Either the id
              or the name must be specified 
        - in: path
          name: name
          schema: 
            type: string
            #minimum: 1
            #maximum: 1
          required: false
          description: |
              Name of the county. Can be either lower or upper case, and also can optionally specify "county" after the base name.
              Can be used to identify a county in the request. Either the id or the name must be specified.
        - in: path
          name: fs
          schema: 
            type: string
            #minimum: 1
            #maximum: 1
          required: true
          description: |
              The filing status of the tax payer. Used for calculating taxes tied with living in the requested county. Must specify 'S', 'M', or 'H' for
              single, married, and head filing status respectively.
        - in: path
          name: res
          schema: 
            type: boolean
            #minimum: 1
            #maximum: 1
          required: true
          description: |
              The residency status of the tax payer. Used for calculating taxes tied with living in the requested county.
        - in: path
          name: dep
          schema: 
            type: integer
            #minimum: 1
            #maximum: 1
          required: true
          description: |
              The number of dependents of the tax payer. Used for calculating taxes tied with living in the requested county.
        - in: path
          name: income
          schema: 
            type: integer
            #minimum: 1
            #maximum: 1
          required: true
          description: |
              The income of the tax payer. Used for calculating taxes tied with living in the requested county.
      responses:
        '200':
          description: This is an example county response. This response is the result of requesting for New York county 
                        for a single resident filer with no dependents and an income of $80,000
          content:
            application/json:
              schema:
                type: object
                example:
                  County_id: 36061,
                  County_name: "New York County"
                  State_id: 36,
                  State_name: "New York"
                  Pop: 1628706
                  Male_pop: 771278
                  Female_pop: 857428
                  Median_income: 93651
                  Average_rent: 1753
                  Commute: 81
                  Tax_locale:
                      Locale_id: 3376
                      Locale_name: "New York City"
                      Total_tax: 19044
                      Federal_tax: 14544
                      State_tax: 4500
                      Locale_tax: 0


  /states:
    get:
      tags:
        - State
      summary: Get survey statistics and taxation estimates for a given state and tax filing input variables.
      consumes: 
        - application/json
      produces: 
        - application/json
      parameters:
        - in: path
          name: id
          schema: 
            type: integer
            #minimum: 1
            #maximum: 1
          required: false
          description: |
              Numeric id tied to the state in the system. Can be used to identify a state in the request. Either the id
              or the name must be specified 
        - in: path
          name: name
          schema: 
            type: string
            #minimum: 1
            #maximum: 1
          required: false
          description: |
              Name of the state. Can be either lower or upper case. Can be used to identify a state in the request. Either the id or the name must be specified.
        - in: path
          name: fs
          schema: 
            type: string
            #minimum: 1
            #maximum: 1
          required: true
          description: |
              The filing status of the tax payer. Used for calculating taxes tied with living in the requested state. Must specify 'S', 'M', or 'H' for
              single, married, and head filing status respectively.
        - in: path
          name: res
          schema: 
            type: boolean
            #minimum: 1
            #maximum: 1
          required: true
          description: |
              The residency status of the tax payer. Used for calculating taxes tied with living in the requested state.
        - in: path
          name: dep
          schema: 
            type: integer
            #minimum: 1
            #maximum: 1
          required: true
          description: |
              The number of dependents of the tax payer. Used for calculating taxes tied with living in the requested state.
        - in: path
          name: income
          schema: 
            type: integer
            #minimum: 1
            #maximum: 1
          required: true
          description: |
              The income of the tax payer. Used for calculating taxes tied with living in the requested state.
      responses:
        '200':
          description: This is an example county response. This response is the result of requesting for New York state 
                        for a single resident filer with no dependents and an income of $80,000
          content:
            application/json:
              schema:
                type: object
                example:
                  State_id: 36
                  State_name: "New York"
                  Pop: 18466230
                  Male_pop: 8953064
                  Female_pop: 9513166
                  Median_income: 77578
                  Average_rent: 1381
                  Commute: 17
                  Total_tax: 19044
                  State_tax: 4500
                  Federal_tax: 14544


  /county-list:
    get:
      tags:
        - County
      summary: Return list of counties ranked by a given metric and ranking criteria.
      consumes: 
        - application/json
      produces: 
        - application/json
      parameters:
        - in: path
          name: metric_name
          schema:
            type: string
            #minimum: 1
            #maximum: 1
          required: true
          description: The name of the metric to rank the counties by. 
        - in: path
          name: size
          schema:
            type: integer
            required: true
          description: The length of the list of the generated response.
        - in: path
          name: desc
          schema:
            type: boolean
            required: true
          description: Boolean defining whether the list should be in descending order.
    responses:
      '200':
        description: This example response is in response to a request for the top 5 counties ordered by commute length descending.
        content:
          application/json:
            schema:
              type: object
              example:
                Metric_name: commute,
                Ranked_list: 
                  - 
                  {
                    "County_id": 36061,
                    "County_name": "New York County",
                    "State_id": 36,
                    "State_name": "New York",
                    "Metric_value": 81
                  },
                  {
                    "County_id": 25025,
                    "County_name": "Suffolk County",
                    "State_id": 25,
                    "State_name": "Massachusetts",
                    "Metric_value": 39
                  },
                  {
                    "County_id": 6075,
                    "County_name": "San Francisco County",
                    "State_id": 6,
                    "State_name": "California",
                    "Metric_value": 36
                  },
                  {
                    "County_id": 51013,
                    "County_name": "Arlington County",
                    "State_id": 51,
                    "State_name": "Virginia",
                    "Metric_value": 33
                  },
                  {
                    "County_id": 13121,
                    "County_name": "Fulton County",
                    "State_id": 13,
                    "State_name": "Georgia",
                    "Metric_value": 31
                  }
                ]
              }

  /state-list:
    get:
      tags:
        - State
      summary: Return list of states ranked by a given metric and ranking criteria.
      consumes: 
        - application/json
      produces: 
        - application/json
      parameters:
        - in: path
          name: metric_name
          schema:
            type: string
            #minimum: 1
            #maximum: 1
          required: true
          description: The name of the metric to rank the states by. 
        - in: path
          name: size
          schema:
            type: integer
            required: true
          description: The length of the list of the generated response.
        - in: path
          name: desc
          schema:
            type: boolean
            required: true
          description: Boolean defining whether the list should be in descending order.

  /county-taxes:
    get:
      tags:
        - County
      summary: Return static taxation information for a given county.
      consumes: 
        - application/json
      produces: 
        - application/json
      parameters:
        - in: path
          name: id
          schema: 
            type: integer
            #minimum: 1
            #maximum: 1
          required: false
          description: |
              Numeric id tied to the county in the system. Can be used to identify a county in the request. Either the id
              or the name must be specified 
        - in: path
          name: name
          schema: 
            type: string
            #minimum: 1
            #maximum: 1
          required: false
          description: |
              Name of the county. Can be either lower or upper case, and also can optionally specify "county" after the base name.
              Can be used to identify a county in the request. Either the id or the name must be specified. 

  /state-taxes:
    get:
      tags:
        - State
      summary: Return static taxation information for a given state.
      consumes: 
        - application/json
      produces: 
        - application/json
      parameters:
        - in: path
          name: id
          schema: 
            type: integer
            #minimum: 1
            #maximum: 1
          required: false
          description: |
              Numeric id tied to the state in the system. Can be used to identify a state in the request. Either the id
              or the name must be specified 
        - in: path
          name: name
          schema: 
            type: string
            #minimum: 1
            #maximum: 1
          required: false
          description: |
              Name of the state. Can be either lower or upper case. Can be used to identify a state in the request. Either the id or the name must be specified.

  /federal-taxes:
    get:
      tags:
        - Federal
      summary: Return static taxation information for federal level taxes.
      consumes: 
        - application/json
      produces: 
        - application/json

  /health:
    get:
      tags:
        - Health
      summary: Health endpoints, returns 200 response response if API is healthy.
